### ISSUE TITLE
Any way to restrict the Annotation to sealed hierarchies of only 1 level of nesting?

### ISSUE THREAD

**Issue by erawhctim** [livefront/sealed-enum#103]
I'd love to introduce this in our project, but set some kind of configuration on the plugin such that its disallows the `@GenSealedEnum` annotation (and fails the build) for sealed classes that have more than 1 level of nesting/class hierarchy. 

Example:
- Allowed: 
    ```
    sealed class Alpha {
        object Beta : Alpha()
        object Gamma : Alpha()
    
        @GenSealedEnum
        companion object
    }
    ```
- Disallowed: 
    ```
    sealed class Alpha {
        sealed class Beta : Alpha() {
            object Delta: Beta()
        }
        object Gamma : Alpha()
    
        @GenSealedEnum
        companion object
    }
    ```
    
Any thoughts? Is that architecturally possible?

**Comment by alexvanyo** [comment]
Hi! Something like that should be possible, but I'm curious to hear your use case for restricting the usage.

At first glance to me, having some sort of "disallow" configuration sounds like something you could lint for if you wanted to avoid nested usage.

**Comment by erawhctim** [comment]
Good idea on lint! That's definitely an option (and probably a more appropriate one)

I was mostly just brainstorming how we might limit the usage of this plugin to only apply to the various sealed classes that act more like an enum (just from the perspective of being defensive).
